name: PaperBasicHome
version: '${version}'
main: me.ventilover.paperbasichome.PaperBasicHome
api-version: '1.20'


commands:
  sethome:
    description: Use to set a new home!
    usage: /sethome
    permission: paperbasichome.sethome
  home:
    description: Teleport to a home
    usage: /home [Home Name]
    permission: paperbasichome.home
  homes:
    description: Lists all homes
    usage: /homes
    permission: paperbasichome.homes

permissions:
  paperbasichome.sethome:
    description: Perm to set a home
    default: true
  paperbasichome.home:
    description: Perm to teleport to an home
    default: true
  paperbasichome.homes:
    description: Perm to list homes
    default: true